import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Header from '../components/Header'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header title={'中学関数アプリ'} link={''} display={'none'}/>
      <h2>menu</h2>
      <Link href="/1_function/home">
        1次関数
      </Link>        
    </div>
  )
}
